### ISSUE TITLE
Not strongly connected at first look but ...

### ISSUE THREAD

**Issue by MatthieuDien** [maciej-bendkowski/paganini#3]
Hi guys,

I have a problem with the following grammar :
spec = Specification()                                                                                                                                                                                    
var0, var1, var2, var3 = Variable(),Variable(),Variable(),Variable()                                                                                                                                       spec.add(var0, var1 * var1 * var1 * var1)                                                                                                                                                                 
spec.add(var1, var2+var2+var2+var2 + var3*var2 + var1 * var1 * var1 * var1)                                                                                                                               
spec.run_singular_tuner(var2) 

It gives me :
ValueError: Given specification has not a strongly connected dependency graph...

But it worked before.

I understand the error, but actually the dependency graph is strongly connected because var0 = var1^4

Is it possible to add an option to pass this check when we know what we are doing ?

Cheers,
Matthieu

**Comment by maciej-bendkowski** [comment]
Both tuning functions expect an additional `Method` parameter, defaulting to `Method.STRICT`.
For instance:

```python
def run_singular_tuner(self, z, params = None, method = Method.STRICT):
```

If you pass `Method.FORCE` instead, all theoretical checks are skipped.
Also, it's not clear to me why you claim that the input graph is strongly-connected.
After all, `var1` does not mention `var0` in its definition, right?

**Comment by MatthieuDien** [comment]
Thanks for the hint, I will add this in my code !

About the strong connectedness, I mean var0 = var1^4, so "mathematically" speaking they are connected : var1 = var0^1/4.
However, I understand that you don't want to handle this kind of border case.

Thanks again for your answer !

**Comment by maciej-bendkowski** [comment]
Just to clarify, please note that the dependency graph is *directed*. There's no border case, as far as I can see. In your particular case we have the following edges:

```
v0 -> v1
v1 -> v2
v1 -> v1
v1 -> v3
```

Such a graph is *not* strongly-connected as there's no directed path connecting, say, `v3` and `v0`. Respective edges are directed and cannot be reversed, which is what I assume you meant with your comment. Note that all states (i.e. variables) are, however, *reachable* from `v0`. You can therefore use finite size tuning, instead. Hope that helps you out.

**Comment by Sergey-A-Dovgal** [comment]
Can I reply from Gmail?
