### ISSUE TITLE
Warning with cvxpy 1.1.1

### ISSUE THREAD

**Issue by Kerl13** [maciej-bendkowski/paganini#4]
Hi Maciej :slightly_smiling_face: 

I recently started getting warnings from cvxpy, complaining about that way paganini uses the `*` operator. For instance, this code:

```python
from paganini import *
spec = Specification()
z, B = Variable(), Variable()
spec.add(B, 1 + z * B * B)
spec.run_singular_tuner(z)
```

triggers the following warning:

```
/home/martin/.local/lib/python3.8/site-packages/cvxpy/expressions/expression.py:516: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)
/home/martin/.local/lib/python3.8/site-packages/cvxpy/expressions/expression.py:516: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.

  warnings.warn(__STAR_MATMUL_WARNING__, UserWarning)
```
The results are correct though, it's probably harmless until next major release of cvxpy.
For the record, I'm using paganini 1.3.2 with cvxpy 1.1.1 and python 3.8.3.

Cheers

**Comment by maciej-bendkowski** [comment]
@Kerl13 We might want to supress these warnings, if that even possible. These warnings also caught my eye recently.

**Comment by Kerl13** [comment]
Ok then I can take a look and open a PR if I manage to suppress them (or part of them). Is that okay with you?

(Sorry that I'm so long to respond, I'm working rather sparsely on my programing projects these days…)

**Comment by maciej-bendkowski** [comment]
@Kerl13 Sure, any PRs are welcome :)

**Comment by Sergey-A-Dovgal** [comment]
One of the ways to make sure everything works correctly is to require a
specific version of cvxpy, but then it is a mess for a user to make sure
the version is correct.

Otherwise, we have to adapt to cvxpy

ср, 17 июн. 2020 г. в 10:20, Maciej Bendkowski <notifications@github.com>:

**Comment by Kerl13** [comment]
I'm pretty confident the changes suggested by the warning message are backward compatible. CVXPY is just starting to deprecate the use of `*` in favour of `@` for matrix multiplication which, I guess(?), must have been working for some time.

Requiring a specific version of cvxpy is probably a bit too strict I agree, but it might be useful to give a lower bound. For instance, cvxpy seems to have changed a lot between versions <1.0 and ≥1.0 so maybe paganini is not compatible with older versions and should require `cvxpy==1.*`. That's just a random guess though, I have not tested it.
